### ISSUE TITLE
Issue with Promise.any

### ISSUE THREAD

**Issue by CallmeHongmaybe** [greatfrontend/greatfrontend#61]
## Your GreatFrontEnd account email (optional)

quanvihong@gmail.com 

## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [ ] Question Solution
- [x] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [x] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

I think the last test case was pretty strict, especially when the alternative solution is 99% similar to the suggested solution. If the alternative solution is wrong in some way, can you talk about this issue in the solution section ? 

## Code you used to submit (where relevant)

```js
/**
 * @param {Array<*|Array>} value
 * @return {Array}
 */
export default function promiseAny(iterable) {
  return new Promise((resolve, reject) => { 
    let rejects = []

    if (!iterable.length) reject(new AggregateError(iterable))

    iterable.forEach(async (item, index) => { 
      try { 
        resolve(await item) // fulfills case 1
      }
      catch (error) { 
          rejects[index] = await error
          if (rejects.length == iterable.length) {
            reject(new AggregateError(rejects))
          }
      }
    })
  })
}
```

## Expected behavior vs Actual behavior (where relevant)

I expect the code to pass all tests. But it turned out that the last test case failed.

**Comment by yangshun** [comment]
It looks 99% similar but it contains a logical flaw. This way of checking completion is wrong because if the last promise is rejected first, `rejects[2]` is assigned and then the `rejects` array now has a length of 3, resulting in `reject()` being called even when the first two promises haven't been settled.

We'll improve the solution writeup to talk why checking the all settled condition using this method is incorrect.
