### ISSUE TITLE
Issue with Compact

### ISSUE THREAD

**Issue by A-simo** [greatfrontend/greatfrontend#71]
## Your GreatFrontEnd account email (optional)

asimo1990@gmail.com 

## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [x] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [x] JavaScript (TypeScript tbh))
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue
I got types error (2322) while solution is correct.
This leads to doubts about one's version of the solution.

## Code you used to submit (where relevant)

```js
export default function compact<T>(
  array: Array<T | null | undefined | false | 0 | ''>,
): Array<T> {
  
  return array.filter(elem => !!elem);
}
```

## Screenshots (where relevant)
![image](https://github.com/greatfrontend/greatfrontend/assets/27725357/d6d235fb-26a7-4ebf-bfca-0c27efa6be95)

**Comment by yangshun** [comment]
Thanks for reporting! However, just because your solution runs correctly doesn't mean it's type-safe. In this case you're right but you need to provide more hints to the TypeScript compiler for such a solution. The [same problem is shown on the TS playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAE2AMwIYFcA29noHYDGMAlhHnARALZipEA8AKgHwAUAUHHKlFKgJ4AuOAEFeApnAA+cPFkzS4+JMmJ5gCRWkwBnYIoAMigOTHmAGnYBKYWL78mzOAG9OcN1GAx0Ucj3sAdKrYwFCswJjAVHAAvE4AhPERUVYA3OwAvkA).

Unfortunately this is not something we can fix on our end.
